version: '3'
services:
  webmushra:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    command: /start-reload.sh
    depends_on:
      - db
    environment:
      MONGO_USERNAME: ***REMOVED***
      MONGO_PASSWORD: ***REMOVED***
  debug:
    build:
      context: .
      dockerfile: debug-docker
    stdin_open: true
    tty: true
    depends_on:
      - db
      - webmushra
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ***REMOVED***
      MONGO_INITDB_ROOT_PASSWORD: ***REMOVED***